### ISSUE TITLE
Cannot remove host

### ISSUE THREAD

**Issue by asm-informatik** [unioslo/zabbix-cli#113]
Using the zabbix-cli I can show host information

![image](https://user-images.githubusercontent.com/51644370/68674194-ad88bc80-0555-11ea-961d-a1b386b5a785.png)

But I cannot use remove_host to remove the host

![image](https://user-images.githubusercontent.com/51644370/68674249-d1e49900-0555-11ea-9afc-bcaf117fde94.png)

Thanks for your help!
Nadine

**Comment by paalbra** [comment]
What happens if you run `remove_host`? I'm not sure if you meant to attach the same picture twice?

Also: It would be nice if you turn on logging in the config and attach the relevant parts of the log in case of an error.

**Comment by asm-informatik** [comment]
I get this

![image](https://user-images.githubusercontent.com/51644370/68681220-5558b700-0563-11ea-834a-50b9561127bf.png)

Where exactly do you want me to turn on logging?

**Comment by paalbra** [comment]
in `~/.zabbix-cli/zabbix-cli.conf` you could configure logging like this:

```
[logging]
logging = ON
log_level = DEBUG
log_file = /tmp/zabbix-cli.log
```
This log will probably have some relevant information. Just strip whatever parts you don't want to share.

**Comment by asm-informatik** [comment]
I suppose I had a problem with that particular host. I deleted it from the GUI and when I tried to delete another host with the CLI to generate logfiles, it worked like a charm.

Sorry, for the inconvenience. If it occurs again, I will post a new issue and provide the logfiles
