### ISSUE TITLE
issue in create_host_interface

### ISSUE THREAD

**Issue by pipol31** [unioslo/zabbix-cli#119]
Hi, 

I'm trying to use the create_host_interface to set the interface in SNMP mode with IP. and it failed with the following error. "Problems creating host interface on JUPITER- "

`create_host_interface JUPITER 1 2 161 220.1.4.119 "" 1`

below the trace in log file

```
2019-12-13 13:59:19,485 [zabbix_cli.cli][None][22772][ERROR]: Problems creating host interface on JUPITER- 
(u'Error -32602: Invalid params.: Invalid IP address "JUPITER". while sending 
{u\'params\': 
{\'hostid\': \'10539\', \'ip\': \'GBCA6B30\', \'useip\': 1, \'dns\': \'\', \'main\': 1, \'type\': 2, \'port\': \'161\'}, 
u\'jsonrpc\': u\'2.0\', u\'method\': u\'hostinterface.create\', u\'auth\': u\'745189ebcb9f46dace0ca7f7712fcbc6\', u\'id\': 8}'
```
, -32602)

I've found the fix.

```
diff --git a/zabbix_cli/cli.py b/zabbix_cli/cli.py
index f004815..33516d5 100644
--- a/zabbix_cli/cli.py
+++ b/zabbix_cli/cli.py
@@ -3174,7 +3174,7 @@ class zabbixcli(cmd.Cmd):
             query["ip"] = ""
             query["dns"] = interface_dns
         elif interface_useip == "1":
-            query["ip"] = interface_dns
+            query["ip"] = interface_ip
             query["dns"] = ""

         try:
```

**Comment by paalbra** [comment]
Thanks. Looks like a copy-paste typo that was introduced while refactoring 75275dc4293aa67188177787b33bc69ea20fa734.

Would you like to submit this as a pull request? If not, I'll add one myself.

PS.
You might want to make sure that auth token is invalid.
