### ISSUE TITLE
 [Error]: Problems giving the admin usergroup while create_hostgroup  

### ISSUE THREAD

**Issue by daemonserj** [unioslo/zabbix-cli#121]
Zabbix 4.0

[zabbix-cli ***@zabbix-ID]$ create_hostgroup  dddd

[Error]: Problems giving the admin usergroup Zabbix administrators RW access to dddd

+--------------------------------------+----------------------------------+
|              Configuration parameter | Value                            |
+--------------------------------------+----------------------------------+
|                       zabbix_api_url | http://*****/zabbix/    |
|                          cert_verify | OFF                              |
|                            system_id | zabbix-ID                        |
|                    default_hostgroup | All-hosts                        |
|              default_admin_usergroup | Zabbix administrators            |
|        default_create_user_usergroup | All-users                        |
| default_notification_users_usergroup | All-notification-users           |
|            default_directory_exports | /root/zabbix_exports             |
|                default_export_format | XML                              |
|    include_timestamp_export_filename | ON                               |
|                           use_colors | ON                               |
|                  use_auth_token_file | OFF                              |
|                           use_paging | OFF                              |
|                              logging | OFF                              |
|                            log_level | INFO                             |
|                             log_file | /root/.zabbix-cli/zabbix-cli.log |
+--------------------------------------+----------------------------------+

**Comment by daemonserj** [comment]
User is a Zabbix suoer administrator

**Comment by paalbra** [comment]
Does the `Zabbix administrators` user group exist in your instance?

If it does: Could you set `log_level` to `DEBUG` and paste relevant output from `log_file`?

**Comment by daemonserj** [comment]
After zabbix reboot the problem was gone
