### ISSUE TITLE
Zabbix 5.4 - could not be imported hosts XML file

### ISSUE THREAD

**Issue by ehno5** [unioslo/zabbix-cli#136]
u'Error -32602: Invalid params.: Invalid parameter "/rules": unexpected parameter "screens". while sending {u\'params\': {u\'rules\': {\'templates\': {\'createMissing\': True, \'updateExisting\': True}, \'valueMaps\': {\'createMissing\': True, \'updateExisting\': True}, \'screens\': {\'createMissing\': True, \'updateExisting\': True}, \'applications\': {\'createMissing\': True}, \'groups\': {\'createMissing\': True}, \'images\': {\'createMissing\': True, \'updateExisting\': True}, \'templateScreens\': {\'createMissing\': True, \'updateExisting\': True}, \'templateLinkage\': {\'createMissing\': True}, \'maps\': {\'createMissing\': True, \'updateExisting\': True}, \'items\': {\'createMissing\': True, \'updateExisting\': True}, \'triggers\': {\'createMissing\': True, \'updateExisting\': True}, \'graphs\': {\'createMissing\': True, \'updateExisting\': True}, \'hosts\': {\'createMissing\': True, \'updateExisting\': True}, \'discoveryRules\': {\'createMissing\': True, \'updateExisting\': True}}, u\'source\': \'<?xml version="1.0" encoding="UTF-8"?

**Comment by paalbra** [comment]
I realize that this issue actually came before, but this is due to lack of 5.4 support. It's mentioned in #139
