### ISSUE TITLE
Add support for Zabbix 5.4

### ISSUE THREAD

**Issue by AleksejsC** [unioslo/zabbix-cli#139]
Zabbix 5.4.4. 
tested zabbix-cli 2.2.1
```
$zabbix-cli -C "show_host *"

[ERROR]:'available

$zabbix-cli -C "show_usergroups"

[ERROR]:'alias'
```
show_hostgroups does work, for instance.

**Comment by Pigi-102** [comment]
Hello.
  same configuration and  same problem here.

**Comment by greenaar** [comment]
^^ The above fixes hosts from limited testing, users will still need to be fixed, with the switch from 'alias' to 'username'.  I'm going to take a look at this as time permits, it should be relatively simple.

**Comment by carlfugate** [comment]
I'm having the same issue on 5.4.9.  Outside of show_alarms nothing else really seems to work.  Is there any roadmap on this?

**Comment by AleksejsC** [comment]
Version 6 of Zabbix brought even more changes to API.

**Comment by mbakke** [comment]
This should be fixed in the latest release, closing!
