### ISSUE TITLE
Problem Creating Maintenance

### ISSUE THREAD

**Issue by prague34** [unioslo/zabbix-cli#145]
Hi,
I get this error when trying to create maintenance definition
('Error -32602: Invalid params.: Invalid parameter "/1/active_since": an unsigned integer is expected. while sending

Welcome to the Zabbix command-line interface (v2.2.1)
Connected to server http://192.168.1.100:9191 (v6.0.3)

**Comment by mbakke** [comment]
Fixed in 2.3.0, thanks!
