### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by rkarlsba** [unioslo/zabbix-cli#150]
# python3 -m zabbix_cli.config show
/usr/lib/python3/dist-packages/zabbix_cli/config.py:114: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  class OptionRegister(collections.Mapping):
DEBUG:__main__:found config '/usr/share/zabbix-cli/zabbix-cli.conf'
DEBUG:__main__:loading config '/usr/share/zabbix-cli/zabbix-cli.conf'
DEBUG:__main__:found config '/root/.zabbix-cli/zabbix-cli.conf'
DEBUG:__main__:loading config '/root/.zabbix-cli/zabbix-cli.conf'

…so I guess this won't work too well with python 3.10

**Comment by mbakke** [comment]
This was fixed in #138 and will be included in the upcoming zabbix-cli release.  Thanks :)
