### ISSUE TITLE
RL8: [ERROR]: 'Version' object has no attribute 'release'

### ISSUE THREAD

**Issue by tjyang** [unioslo/zabbix-cli#182]
Recording this error for python3-packaging-16.8-9.el8.noarch on RockyLinux 8

```
[me@alt01 tmp]$ zabbix-cli
-------------------------
Zabbix-CLI authentication
-------------------------
# Username[me]: Admin
# Password:

[ERROR]: 'Version' object has no attribute 'release'

[me@alt01 tmp]$
```
- [create own rpm](https://github.com/unioslo/zabbix-cli/commit/cf7d2092aaead26b831b772337f5ea73b9b84764)
- installed rpms
```
[me@alt01 tmp]$ rpm -qa |egrep "zabbix-cli|python3-requests|python3-packaging"
zabbix-cli-2.3.2-1.el8.noarch
python3-packaging-16.8-9.el8.noarch
python3-requests-2.20.0-3.el8_8.noarch
[me@alt01 tmp]$
```
- Google search on the error message

R1: https://github.com/pypa/setuptools_scm/issues/605

**Comment by pederhan** [comment]
I don't know if I have the capacity to maintain the RPM package. It is very limiting to deal with such outdated dependencies - that version of [packaging](https://pypi.org/project/packaging/) is over 7 years old at this point. Install with pip for now.
