### ISSUE TITLE
Issue with creating/updating user macro

### ISSUE THREAD

**Issue by xenosmurfen** [unioslo/zabbix-cli#228]
I can't for the life of me create or update user macros that seemingly exist in templates. For instance {$VMWARE.VM.UUID}

in zabbix-cli the command seems to execute fine, but no macro is created on the host. With or without the template that has this macro defined (in this case VMware Guest)

![Image](https://github.com/user-attachments/assets/f6b13eb2-2f8a-461d-9ab3-55a6caa12a60)

I hope I'm just doing something wrong here.

Thanks to the devs for this great tool!

**Comment by pederhan** [comment]
Thank you for finding this issue. It should be fixed in #231. I'll try to publish a new version in the coming days.

**Comment by xenosmurfen** [comment]
Great! Thanks for the swift reply!
