### ISSUE TITLE
Update host description

### ISSUE THREAD

**Issue by xenosmurfen** [unioslo/zabbix-cli#235]
This is somewhere between a question and a feature-request :)

I see it's possible to define a description when creating a new host, so I was trying to maybe update a description on an existing host with no success. As expected really.

![Image](https://github.com/user-attachments/assets/f03365be-9cdb-47bc-a73d-5497653b8362)

But, is there a way to update just the description with zabbix-cli that I'm missing? Or are only the inventory fields updatable as of now?

**Comment by pederhan** [comment]
You are right, there is no command for updating existing hosts. When I rewrote Zabbix-CLI I mainly focused on porting existing commands from V2, so missing commands for common operations is a bit of a blind spot for me. 

I'll look into adding this and other common operations ASAP.

**Comment by xenosmurfen** [comment]
Great, thanks again for the quick reply :)

**Comment by pederhan** [comment]
Added in #242. I probably won't publish a new version just yet though - there are quite a few changes in master that I need to properly test first.
