### ISSUE TITLE
login --token keeps requesting username and password

### ISSUE THREAD

**Issue by sur5r** [unioslo/zabbix-cli#253]
After using `zabbix-cli init` to set the url, `zabbix-cli login --token XXX` keeps asking for username and password. Setting the token manually in the config file works.

From a cursory look at the code, it seems both `init_config` and `login` do not containt the right logic to work correctly in this scenario.

**Comment by pederhan** [comment]
`login` is only meant to be used in the REPL to prompt for re-authentication when a session is expired, or to re-authenticate as a different user. The `login` command does contain some bugs with regards to expired sessions, but its core functionality is as expected. I will look into disabling it outside the REPL to avoid confusion.

To log in with an API token check the documentation: https://unioslo.github.io/zabbix-cli/guide/authentication/#token

We might add a `zabbix-cli --token` option in the future, but for now, those are the only ways to log in with an API token.

**Comment by sur5r** [comment]
I see. Thanks!
