### ISSUE TITLE
zabbix 7.2 authentication not possible anymore?

### ISSUE THREAD

**Issue by miconx** [unioslo/zabbix-cli#274]
i think the authentication with api key in release 7.2 has changed 
in my case i cannot login via zabbix-cli anymore 
(even tried newly created  API-key)

**Comment by pederhan** [comment]
I'll investigate.

**Comment by pederhan** [comment]
This should be fixed in [3.4.2](https://github.com/unioslo/zabbix-cli/releases/tag/3.4.2).
