### ISSUE TITLE
Maintenance definition showing unexpected behavior

### ISSUE THREAD

**Issue by iftitutul** [unioslo/zabbix-cli#64]
I am using zabbix-cli 1.7 but if I want to create maintenance window any hosts it seems unexpected behavior. 
Sometimes maintenance definition done successfully and sometimes it shows error. 

here, Maintenance definition created with time 12.00-13.00.
```
[zabbix-cli Admin@zabbix-ID]$ create_maintenance_definition 'zabbixdownall' 'down all 1 hour' 'Windows-local' '2018-04-23T12:00 to 2018-04-23T13:00' 1

[Done]: Maintenance definition with name [zabbixdownall] created
```
but **time shows wrong** in zabbix side **22.00-23.00**

```
zabbixdownall | No data collection | 2018-04-23 22:00 | 2018-04-23 23:00 | Approaching | down all 1 hour
-- | -- | -- | -- | -- | --
```

Another error for creating maintenance windows for hosts:
```
[zabbix-cli Admin@zabbix-ID]$ create_maintenance_definition 'ansible down' 'down all 1 hour' 'Ansible-server' '2018-04-24T01:00 to 2018-04-24T03:00' 1

[Error]: Problems creating maintenance definition (ansible down)

```

Kindly help me to use zabbix-cli more widely

Thanks

**Comment by paalbra** [comment]
@iftitutul I realize that this is an old issue. Did you manage to resolve this problem?

If you're still experiencing this issue:

What's the local timezone of the computer you're running zabbix-cli on?

Could you enable debug logging and provide the log of the last command where you get the error?

**Comment by paalbra** [comment]
Closing due to lack of feedback
